### ISSUE TITLE
New app

### ISSUE THREAD

**Issue by orenatan** [natekspencer/BwaSpaManager#3]
Any solutions to the new app?

**Comment by natekspencer** [comment]
> Any solutions to the new app?

Unfortunately I don't have any current plans of updating this for compatibility with the new app. After a couple of internet outages at home and realizing that SmartThings still fully relies on cloud support to even open the app so I can control my local z-wave devices, I decided to invest in a home automation solution that could still function as long as my home network remained online and also allowed me more flexibility in local control of devices and automations.

**Comment by orenatan** [comment]
Thanks

Do you mean HA?

Oren Nathan
073-107 59 61
orenatan@gmail.com

**Comment by natekspencer** [comment]
Yes, HomeAssistant is what I migrated to for my current setup.

**Comment by orenatan** [comment]
Nice. Whos intigration are you using?

**Comment by natekspencer** [comment]
I started with https://github.com/garbled1/balboa_homeassistan and helped build out more functionality. It's nice that it doesn't require a cloud API but just uses your local network to connect and control the spa. Way more responsive and up to date.

**Comment by orenatan** [comment]
Everything you wrote is true, just the Balboa local connection don't work
as stable as the cloud for some reason.

orenatan@gmail.com

**Comment by natekspencer** [comment]
The cloud obfuscates the local connection issues because the local connection issues will still exist. For instance, if the tub goes offline (which it frequently does), then the local connection won't work. The cloud, however, will still show you the most recent data it had retrieved and happily send commands (without them functioning). It doesn't mean your spa is actually working though or that what is being reported is entirely correct.

**Comment by orenatan** [comment]
Thanks for the explanation !

Med Vänliga Hälsningar
Oren Nathan
073 - 107 59 61
orenatan@gmail.com

**Comment by Dawsonshi** [comment]
Its too bad you are not supporting this app anymore. I appreciate you efforts.  It almost works on the new SmartThings app and it works with Alexa.  The only problem is it wont let me set the target temperature above 95 degrees.   I wish I could get it to go to 102.  If it did it would be useful "enough" to say Alexa, turn on the hot tub".  Is this something I can fix?  Thanks for everything.
